USE [Social_Network_DB]
GO

CREATE TABLE [dbo].[Post]
(
	ID				UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	UserID			UNIQUEIDENTIFIER	NOT NULL,
	Content			NVARCHAR(MAX)		NOT NULL,
	FeelingStatus	TINYINT				NULL,
	PrivacyStatus	TINYINT				NOT NULL,
	IsDeleted		BIT					NOT NULL,
	CreatedDate		DATETIME			NOT NULL,
	ModifiedDate	DATETIME			NOT NULL
)