USE [Social_Network_DB]
GO

CREATE TABLE [dbo].[UserFriend]
(
	ID			UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	UserID		UNIQUEIDENTIFIER	NOT NULL,
	FriendID	UNIQUEIDENTIFIER	NOT NULL,
	IsDeleted			BIT			NOT NULL,
	CreatedDate			DATETIME	NOT NULL,
	ModifiedDate		DATETIME	NOT NULL,
	CONSTRAINT FK_UserOwner FOREIGN KEY (UserID) REFERENCES [dbo].[User](ID),
	CONSTRAINT FK_UserFriend FOREIGN KEY (FriendID) REFERENCES [dbo].[User](ID)
)