USE [Social_Network_DB]
GO

CREATE TABLE [dbo].[Message]
(
	ID			UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	SenderID	UNIQUEIDENTIFIER	NOT NULL,
	ReceiverID	UNIQUEIDENTIFIER	NOT NULL,
	Content		NVARCHAR(MAX)		NOT NULL,
	IsDeleted			BIT			NOT NULL,
	CreatedDate			DATETIME	NOT NULL,
	ModifiedDate		DATETIME	NOT NULL,
	CONSTRAINT FK_MessageSender FOREIGN KEY (SenderID) REFERENCES [dbo].[User](ID),
	CONSTRAINT FK_MessageReceiver FOREIGN KEY (ReceiverID) REFERENCES [dbo].[User](ID)
)